### PR TITLE
Clear matches

### LINKED ISSUE #195: Popup window reopen on <BS>, continuing typing and close if at the beginning of word.
Firstly, let me thank you for developing this plugin! It is the only reason I didn't give up tweaking my dotfiles to make vim autocompletion work like in JetBrains IDEs.

As for the issue:
* popup window vanishes after pressing backspace
* popup window is not brought back on continuing typing
* autocompletion is called even with zero typed word characters

So, when I start tying in insert mode:
image
And then press <BS> to delete last typed symbol on the left of cursor. And popup suddenly vanishes:
image
Retyping last deleted symbol does not brings popup back:
image
The only way to bring popup back is to delete current word:
image
And here we come to the the second issue: I do not want to trigger autocompletion for empty word. Is it possible to add support for customization of the length of prefix which triggers autocompletion?

I've skimmed source code and found [`b:asyncomplete_refresh_pattern`](https://github.com/prabirshrestha/asyncomplete.vim/blob/1f8d8ed26acd23d6bf8102509aca1fc99130087d/autoload/asyncomplete.vim#L288) which can be the possible solution, but I didn't manage the right value for this pattern.

In my `init.vim`:

```vim
  Plug 'prabirshrestha/async.vim'
  Plug 'prabirshrestha/vim-lsp'
    let g:lsp_diagnostics_enabled          = v:true
    let g:lsp_diagnostics_echo_cursor      = v:true
    let g:lsp_diagnostics_echo_delay       = 200
    let g:lsp_signs_enabled                = v:true
    let g:lsp_signs_error                  = { 'text': '>>' }
    let g:lsp_signs_warning                = { 'text': '--' }
    let g:lsp_signs_hint                   = { 'text': '..' }
    let g:lsp_virtual_text_enabled         = v:false
    let g:lsp_highlight_references_enabled = v:true
    let g:lsp_signature_help_enabled       = v:true
    let g:lsp_async_completion             = v:true

    " Close preview window with <esc>
    autocmd User lsp_float_opened nmap <buffer> <silent> <Esc>
      \ <Plug>(lsp-preview-close)
    autocmd User lsp_float_closed call lsp#ui#vim#references#highlight(v:false)
      \ | nunmap <buffer> <Esc>

    if executable('gopls')
      augroup LspGo
        autocmd!
        autocmd User lsp_setup call lsp#register_server({
          \ 'name': 'gopls',
          \ 'cmd': {server_info->['gopls']},
          \ 'whitelist': ['go'],
          \ })
        autocmd BufWritePre *.go LspDocumentFormatSync
      augroup END
    endif

  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
    let g:asyncomplete_auto_popup       = v:true
    let g:asyncomplete_auto_completeopt = v:false

    set completeopt=menuone,noinsert,noselect

    function! s:on_lsp_buffer_enabled() abort
      setlocal omnifunc=lsp#complete
      setlocal signcolumn=yes

      highlight lspReference cterm=underline

      nnoremap <buffer> <silent> <C-]>                    <Cmd>LspDefinition<CR>
      inoremap <buffer> <silent> <C-]>                    <Cmd>LspDefinition<CR>
      nnoremap <buffer> <silent> <C-LeftMouse> <LeftMouse><Cmd>LspDefinition<CR>
      inoremap <buffer> <silent> <C-LeftMouse> <LeftMouse><Cmd>LspDefinition<CR>

      nnoremap <buffer> <Leader>lu <Cmd>LspReferences<CR>
      nnoremap <buffer> <Leader>lr <Cmd>LspRename<CR>
      nnoremap <buffer> <Leader>lh <Cmd>LspHover<CR>
    endfunction

    augroup lsp_install
      autocmd!
      autocmd User lsp_buffer_enabled call <SID>on_lsp_buffer_enabled()
      autocmd User lsp_complete_done  call asyncomplete#close_popup()
    augroup END
```

### LINKED ISSUE #212: Spaces don't start new completion word
Something I overlooked with #135. A non-keyword character should close a previously opened menu, but that's not happening; instead it stays open until the minimum characters have been typed in the next word:

Screen Shot 2020-08-09 at 2 52 01 PM

### PR DESCRIPTION
**Pull request by ii41**
This PR intends to close #195. I think it can also close #212.

Can't figure out what the "skip popup" logic is for so removed it for simplicity... Maybe for race conditions where when `close_popup`/`cancel_popup` is called and a completion is still being calculated in the background?  Whatever it is for I'm willing to add that back with something that is hopefully less confusing...

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Thanks for the PR. I will let this PR sit for couple of days but I'm using this branch locally. If stable and don't find bugs will merge.

**Comment by prabirshrestha** [comment]
Merged. Been pretty stable for 2 days.

Thanks for the PR.

**Comment by prabirshrestha** [comment]
Actually I had to revert this commit. https://github.com/prabirshrestha/asyncomplete.vim/pull/229.

It breaks `inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() : "\<CR>"`

When you press `<CR>` we mark skip popup so it doesn't show a new popup else you can't add a new line at all since the popup keeps appearing. Feel free to try another PR.

**Comment by ii41** [comment]
> Actually I had to revert this commit. #229.
> 
> It breaks `inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() : "\<CR>"`
> 
> When you press `<CR>` we mark skip popup so it doesn't show a new popup else you can't add a new line at all since the popup keeps appearing. Feel free to try another PR.

I'm a bit confused... I don't see this line in the repo. My understanding is that a user will add this line if they want to let `<CR>` enter a newline when the pum is open, but that is already the behavior before they add this line. So why do we want to support this line of setting?

**Comment by prabirshrestha** [comment]
This doesn't add `<CR>`. When a popup is visible `<CR>` will close the popup.
`inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() : "\<CR>"` 

This is usually used by pressing `tab`  to select the item and then `enter` to close the popup menu. The user can then press `<CR>` again if they want a new line since `pumvisible()` is now false or press `<space>` if they want to continue on the line.

If the user wants to add another `<CR>` with concat.

`inoremap <expr> <CR> pumvisible() ? asyncomplete#close_popup() . "\<CR>" : "\<CR>"` .

I'm interested in the first one.

**Pull request merged**
