### PR TITLE
add fuzzy matching via lua and fts_fuzzy_match.lua

### PR DESCRIPTION
**Pull request by prabirshrestha**
**Do not merge**

This is me trying out fuzzy search. I would need to dog-food this more before I merge to master. Would most likely need a refactor too.

fuzzy-matching

Fuzzy only works if lua is supported. Currently doesn't yet work in neovim so it should fallback to prefix search.

Related blog post about https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb

### CODE REVIEW

**Comment by renstrom** [comment]
I guess this is a prerequisite for Neovim support: https://github.com/neovim/neovim/pull/4411

**Comment by prabirshrestha** [comment]
@renstrom Yes. Waiting for neovim support before I finally merge this. Also there are some improvements that I would like to squeeze too. I have been using `Plug 'prabirshrestha/asyncomplete.vim', { 'branch': 'fuzzy' }` for vim8 for few weeks and has been working well for me. 

@roxma seems to have converted ncm to use `completefunc` and `omnifunc` instead which means every keypress actually calls the complete func we can just sort there. Currently I don't like my implementation of when fuzzy search is called. My original implementation when using async completion was using it `omnifunc` https://gist.github.com/prabirshrestha/0b3b7b4e2112c662979bfeeec4e1edb7. I will continue to play with this a bit more.

**Comment by tutysara** [comment]
looks like neovim/neovim#4411 is merged

**Comment by roxma** [comment]
> @roxma seems to have converted ncm to use completefunc and omnifunc instead which means every keypress actually calls the complete func we can just sort there. 

The reason that I use omnifunc or completefunc instead of `complete()` call for fuzzy matching, is to reduce the popup menu flickering, see 
https://github.com/roxma/nvim-completion-manager/issues/8#issuecomment-279297329

If the menu is opened by `complete()` call, vim will auto hide it when the typed string and the popup menu item don't match by  prefix. And then the completion plugin open the menu again. And again, and again as the user keeps typing.

`omnifunc` and `completefunc` is pretty much the same thing, except that they are triggered by different keys, and  completefunc also remap the `<c-u>` key. Use `omnifunc` when you want to use the `<c-u>` key for something else.

**Comment by prabirshrestha** [comment]
@roxma thanks for the explanation. Does that mean that if vim and neovim patches `complete()` so it doesn't close if it is already open it would solve the flickering issue? If so I would rather wait for vim to have the patch than update to `omnifunc` or `completefunc` as the api `call complete(startcol, candidates)` seems to be much cleaner.

@tutysara Lua support in neovim is merged which is awesome, but seems like `has('lua')` returns false. But currently due to flickering issue, my priority would be to solve this before adding lua fuzzy matcher. I have also been thinking whether to support async matcher api instead of just sync matcher api. This way anyone can extend the matcher and sorter to their needs.

**Comment by tutysara** [comment]
> @tutysara Lua support in neovim is merged which is awesome, but seems like has('lua') returns false. But currently due to flickering issue, my priority would be to solve this before adding lua fuzzy matcher. I have also been thinking whether to support async matcher api instead of just sync matcher api. This way anyone can extend the matcher and sorter to their needs.

Sure thanks, good idea to have the matcher and sorter separate and allow user to extend/substitute them. I haven't looked much into the code. I came here from the lsp repo, I was looking for an lsp impl for vim to setup with java lsp server. I will watch for updates from here as well

**Comment by prabirshrestha** [comment]
I'm waiting for [calling complete() flickers if popup menu is already open](https://github.com/vim/vim/issues/1713) in vim and neovim to be fixed first. Will give it around a month or so if not I may have to first migrate to `completefunc` or `omnifunc` :( before merging this PR.

In the meantime people can continue to use this branch if they want fuzzy matching with lua. I have been using this branch as default in my vimrc and haven't had much problems.

**Comment by purpleP** [comment]
If you want to have good fuzzy matching checkout https://github.com/jhawthorn/fzy It's better than `fzy` `selecta`. It uses the same algorithm used for DNA matching I believe, although with customisations.

**Comment by tracyone** [comment]
Any process?

This feature has lua dependency?

**Comment by prabirshrestha** [comment]
Closing this in favor of https://github.com/prabirshrestha/asyncomplete.vim/pull/49. Feel free to give that a try, It has fuzzy completion enabled.
You need to have vim 8 with `TextChangedP` support. Patch to neovim is also getting ported.

**Pull request closed without merging**
