### PR TITLE
Add "asyncomplete#close_popup()" function for V2 (Ported #98) 

### PR DESCRIPTION
**Pull request by ishitaku5522**
Ported #98 for V2

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Could you also add documentation on this.

Also in v2 `on_change` is called on every keystroke.

**Comment by ishitaku5522** [comment]
Updated document.  I'm not a native English speaker, so please fix grammer if there are some problems.

> Also in v2 on_change is called on every keystroke.

As far as I checked, it has no problem

**Comment by prabirshrestha** [comment]
@ishitaku5522 Could you update `_force_refresh` to reset the flag?

**Comment by prabirshrestha** [comment]
@ishitaku5522 Any update on this?

**Comment by ishitaku5522** [comment]
Sorry, I was busy these days. How about this?

**Comment by prabirshrestha** [comment]
@ishitaku5522 no worries. I tried the PR and `<c-e>` works but as soon as I type the next char it re-opens the menu. Is this the behavior we want? I was thinking that it would stop showing the popup until the trigger character is pressed or force refresh is called. This means `let s:should_skip_next_completion = 0` should not be set in `s:should_skip` but in force_refresh and here when the trigger character is entered. https://github.com/prabirshrestha/asyncomplete.vim/blob/9d75c6872efa370bd3e8efe47089a5c22f487a3c/autoload/asyncomplete.vim#L230-L233

**Comment by prabirshrestha** [comment]
Seems like this got closed automatically because v2 branch got deleted and I can't reopen the PR. Could you send a new one directly to master.

**Comment by ishitaku5522** [comment]
Ok, I see,  finally I understood what you mean now. I tried to put `let s:should_skip_next_completion = 0` at that part simply, but when I insert new word after `<C-y><space>`(close and insert space), the popup for a new word will not be re-opened. I think the popup should open for next word, right? Could you wait until this weekend to fix this? (Or, if you don't want to wait futher, you can fix it.)

**Comment by prabirshrestha** [comment]
Sure. Take your time.

**Comment by ishitaku5522** [comment]
I made new PR as #134

**Pull request closed without merging**
