### PR TITLE
Support custom filter

### PR DESCRIPTION
**Pull request by mattn**
Currently, asyncomplete support only prefix-match-filter. But I want contains-filter.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
how is the perf?

I had explicitly not made the default preprocessor smart because it could be slow and hence provide way to extend it.

**Comment by mattn** [comment]
The main purpose of this pull-request is to want a prefix match or a contains match, depending on the source. For example:

https://github.com/mattn/asyncomplete-google-suggest.vim/

Yesterday, I wrote asyncomplete source using Google Suggest. But most of candidates are removed since the result does not matches with the pre-typed text. (Because the result is japanese text). So I want to add a way to make own filter.

**Comment by prabirshrestha** [comment]
Is `g:asyncomplete_preprocessor` not enough?

https://github.com/prabirshrestha/asyncomplete.vim/blob/312861e9f9725a551ed2223c1d391b5585ad7362/doc/asyncomplete.txt#L57-L89

**Comment by mattn** [comment]
Whether want to use prefix-filter or contains-filter depends on the author of each source, I think.

**Comment by prabirshrestha** [comment]
What if we introduce `let g:asyncomplete_fuzzy = 1` and if it exists use `matchfuzzy()`. This way we don't need to introduce `filter` and if someone really wants it they could create custom preprocessor. It is up to custom preprocessor to honor `g:asyncomplete_fuzzy`

**Comment by mattn** [comment]
Custom filter like mine above is not match anything with matchfuzzy since I want to match `a` with `あ` (It is pronounced a)

**Comment by prabirshrestha** [comment]
@mattn looks good to me. Makes sense for `kanji` characters. Feel free to merge.

**Comment by mattn** [comment]
Thank you!

**Pull request merged**
