### PR TITLE
Only run complete() if the list of candidates has changed

### LINKED ISSUE #109: Don't run complete() if list of candidates hasn't changed
The popup menu is updated (at least) once every time text is inserted, even if the list of candidates hasn't changed. This shouldn't happen; the menu should only update if the list of candidates is different.

May be a solution to #108.

### PR DESCRIPTION
**Pull request by jsit**
Closes #109

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@jsit I'm going to currently hold on your PR changes because for months I have been wanting to rewrite asyncomplete.vim from all the lessons I have learned writing it in the first place. It almost has nothing yet but will lot of features and make it easy to maintain too. WIP can be found at https://github.com/prabirshrestha/asyncomplete.vim/tree/v2

**Comment by jsit** [comment]
Thanks, will take a look at the `v2` branch. Does anything special need to happen to get it set up and working in Vim?

**Comment by prabirshrestha** [comment]
If you are using vim-plug as your plugin manager you can set the branch as v2 else manually switch to `v2` branch locally.

```vim
Plug 'prabirshrestha/asyncomplete.vim', { 'branch': 'v2' }
Plug 'prabirshrestha/asyncomplete-buffer.vim'

let g:asyncomplete_log_file = expand('/tmp/asyncomplete.log')

au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
  \ 'name': 'buffer',
  \ 'whitelist': ['*'],
  \ 'completor': function('asyncomplete#sources#buffer#completor'),
  \ 'triggers': {'*': ['::', '->', '=>', '.']},
  \ }))
```

It is at a very early stage and the only thing that will work is logs.

`TextChangedP` is another branch that I was experimenting last time but had to revert due to bugs. https://github.com/prabirshrestha/asyncomplete.vim/tree/TextChangedP PR: https://github.com/prabirshrestha/asyncomplete.vim/pull/49

Even thought it is going to be v2, the sources api will not change so should be backward compatible.

**Comment by prabirshrestha** [comment]
In v2 the popup menu will be updated all the time because of the custom filtering function. Currently I only do prefix filtering but the goal of v2 is to allows users to allow custom filtering function which means it needs to be done per keystroke. Please have a look at v2 branch and let me know if you can improve perf further.

**Comment by jsit** [comment]
Superseded by #123

**Pull request closed without merging**
