### PR TITLE
Only run complete() if the list of candidates has changed

### LINKED ISSUE #109: Don't run complete() if list of candidates hasn't changed
The popup menu is updated (at least) once every time text is inserted, even if the list of candidates hasn't changed. This shouldn't happen; the menu should only update if the list of candidates is different.

May be a solution to #108.

### PR DESCRIPTION
**Pull request by jsit**
Closes #109

### CODE REVIEW

**Comment by prabirshrestha** [comment]
What are the cases when candidates will not be the same in v2?

In v2 we have custom filter function that does prefix matching instead of vim doing the prefix match which mean the candidates will always change on every keystroke. Do we still need this check?

**Comment by jsit** [comment]
In a Vimscript file, for instance, if I start typing `comple`, I get a popup with the following options (from Omni):

screen shot 2019-03-03 at 1 42 57 pm

If I then type `t` so that the string is `complet`, the list of results is the same:

screen shot 2019-03-03 at 1 43 01 pm

In this case, I don't want to call the `complete` function again, because it's just a waste of CPU.

**Comment by prabirshrestha** [comment]
Doesn't this line always cause the current candidate to to be different? Since we are creating a new instance of `l:items` to be different everytime during a keystroke?

https://github.com/prabirshrestha/asyncomplete.vim/blob/070616b96eebe09ccb06162563a913e3ee54131e/autoload/asyncomplete.vim#L380-L391

Might be try adding log for the check to see if it is actually working here.

https://github.com/prabirshrestha/asyncomplete.vim/blob/070616b96eebe09ccb06162563a913e3ee54131e/autoload/asyncomplete.vim#L398-L400

**Comment by jsit** [comment]
Added a log entry; it is firing for me when I recreate the example I gave above.

**Comment by prabirshrestha** [comment]
The reason for this is because in v2, I want `g:asyncomplete_preprocessor` to be called on every keystroke. I have added docs for this in case you are curious. This enables other features such as removing duplicates, custom filter algorithm such as fuzzy search to be enabled on user space. If we don't do filter, vim will still use prefix matching which means CPU cycles will get used. Rather than vim doing the filter in v2 I made the preprocessor func always filter. While it run vimscript instead of C code for filtering this allows us to have asyncomplete core simple and there is only one way to filter.

https://github.com/prabirshrestha/asyncomplete.vim/blob/1eacfe20b68d48f0168b83b3df0e008054a15ba3/doc/asyncomplete.txt#L55

You might also be intersted in https://github.com/vim/vim/issues/1713 and https://github.com/roxma/vim/commit/3080177c3491e270051fd1e985cf719c86058b5a

**Comment by jsit** [comment]
> I want `g:asyncomplete_preprocessor` to be called on every keystroke

_That_ function will still run that on every keystroke; this PR is just preventing `complete()` from being called if the items haven't changed.

**Comment by prabirshrestha** [comment]
Seems like this got closed automatically because v2 branch got deleted.

**Pull request closed without merging**
